### ISSUE TITLE
Doesn't work with subdirectories on Windows 8/10

### ISSUE THREAD

**Issue by Alexa905** [mr-doc/mr-doc#99]
folder structure:
```javascript
src/app.js
src/client-app/eq.js
```

```javascript
D:\projects\fulcrum>mr-doc -s src -o docs
Mr. Doc [info]: Using theme [mr-doc-theme-default]
Mr. Doc [info]: - Rendering template.
Error: ENOENT: no such file or directory, open 'D:\projects\fulcrum\docs\client-app\eq.js.html'
    at Error (native)
    at Object.fs.openSync (fs.js:584:18)
    at Object.fs.writeFileSync (fs.js:1224:33)
    at C:\Users\user\AppData\Roaming\npm\node_modules\mr-doc\src\mr-doc.js:159:52
    at C:\Users\user\AppData\Roaming\npm\node_modules\mr-doc\node_modules\mkdirp\index.js:48:26
    at FSReqWrap.oncomplete (fs.js:82:15)
```
Now it generates docs only for src/app.js

When I add the folder 'client-app' to ignore (--ignore client-app) it does work correctly. Could you please add the opportunity to work with subdirectories on Windows?

**Comment by iwatakeshi** [comment]
@Alexa905 Thanks for the report :). #100 should fix the issue. It'll be published soon. :)

**Comment by Alexa905** [comment]
@iwatakeshi  Thank you very much for your quick response! 
But It's still not working for me if I have more than one subdirectory, e.g. src/client-app/lib/event-emitter.js Could you please review this case?

**Comment by iwatakeshi** [comment]
Sure, I had a feeling this was going to happen. Haha. Yesterday's fix was a quick fix for subdirectories but it didn't handle other nth subdirectories. I'll look into this case and see if I can walk through the subdirectories.

**Comment by iwatakeshi** [comment]
@Alexa905 #101 Should fix your issue now. It *should* also document files that are in sub-sub directories. If you still encounter other issues, check out the source files and see if you can PR a fix. :)
